#############################################################################
# Makefile for building: ThreeBxConverter.app/Contents/MacOS/ThreeBxConverter
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  ../ThreeBxConverter/ThreeBxConverter.pro
# Template: app
# Command: /Users/christopherforte/Qt/5.10.1/ios/bin/qmake -o ThreeBxConverter.xcodeproj/project.pbxproj ../ThreeBxConverter/ThreeBxConverter.pro -spec macx-xcode CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -after QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=F37PQM36J6
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/christopherforte/Qt/5.10.1/ios/bin/moc
UIC       = 
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_COMPILER_SUPPORTS_SSE2 -DQT_DEPRECATED_WARNINGS -DQZXING_LIBRARY -DZXING_ICONV_CONST -DDISABLE_LIBRARY_FEATURES -DQZXING_MULTIMEDIA -DQZXING_QML -DNOFMAXL -DNO_ICONV -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_QML_DEBUG
INCPATH       = -I../ThreeBxConverter -I. -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/common/uikit -I../Core -I../ThreeBxConverter/QzXing -I../ThreeBxConverter/QzXing/zxing -I/Users/christopherforte/Qt/5.10.1/ios/include -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQuick -I/Users/christopherforte/Qt/5.10.1/ios/include/QtMultimedia -I/Users/christopherforte/Qt/5.10.1/ios/include/QtGui -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQml -I/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork -I/Users/christopherforte/Qt/5.10.1/ios/include/QtCore -I. -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/macx-ios-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_qml.cpp moc_ImageHandler.cpp moc_QZXing.cpp moc_QZXingFilter.cpp\
	 moc_platforminformation.cpp moc_threshodltools.cpp moc_downloadworker.cpp\
	 moc_useraccount.cpp
compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: ../ThreeBxConverter/qml.qrc \
		/Users/christopherforte/Qt/5.10.1/ios/bin/rcc \
		../ThreeBxConverter/QrScannerView.qml \
		../ThreeBxConverter/DashboardListModel.qml \
		../ThreeBxConverter/CryptoWalletDelegate.qml \
		../ThreeBxConverter/DashboardPage.qml \
		../ThreeBxConverter/main.qml \
		../ThreeBxConverter/assets/digibyteIcon.png \
		../ThreeBxConverter/assets/testnetBitcoinIcon.png \
		../ThreeBxConverter/assets/qrScannerGuides.png \
		../ThreeBxConverter/assets/rippleIcon.png \
		../ThreeBxConverter/assets/clipboardPasteIcon.png \
		../ThreeBxConverter/assets/bitcoinCashIcon.png \
		../ThreeBxConverter/assets/litecoinIcon.png \
		../ThreeBxConverter/assets/dashIcon.png \
		../ThreeBxConverter/assets/moneroIcon.png \
		../ThreeBxConverter/assets/ethereumIcon.png \
		../ThreeBxConverter/assets/threebxLogo.png \
		../ThreeBxConverter/assets/zencashIcon.png \
		../ThreeBxConverter/assets/infoIcon.png \
		../ThreeBxConverter/assets/dogeIcon.png \
		../ThreeBxConverter/assets/whiteBackButtonIcon.png \
		../ThreeBxConverter/assets/backButtonIcon.png \
		../ThreeBxConverter/assets/addWalletIcon.png \
		../ThreeBxConverter/assets/bitcoinIcon.png \
		../ThreeBxConverter/assets/threshodlLogo_landing.png \
		../ThreeBxConverter/assets/emailIcon.png \
		../ThreeBxConverter/assets/downNavArrowIcon.png \
		../ThreeBxConverter/assets/brightBitcoinIcon.png \
		../ThreeBxConverter/assets/testnetLitecoinIcon.png \
		../ThreeBxConverter/assets/sureRemitIcon.png \
		../ThreeBxConverter/assets/mailButtonIcon.png \
		../ThreeBxConverter/assets/scanQrButtonIcon.png \
		../ThreeBxConverter/assets/upNavArrowIcon.png \
		../ThreeBxConverter/assets/zcashIcon.png \
		../ThreeBxConverter/assets/settingsButtonIcon.png \
		../ThreeBxConverter/assets/darkBitcoinIcon.png \
		../ThreeBxConverter/assets/refreshButtonIcon.png \
		../ThreeBxConverter/assets/lumensIcon.png
	/Users/christopherforte/Qt/5.10.1/ios/bin/rcc -name qml ../ThreeBxConverter/qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_ImageHandler.cpp moc_QZXing.cpp moc_QZXingFilter.cpp moc_platforminformation.cpp moc_threshodltools.cpp moc_downloadworker.cpp moc_useraccount.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ImageHandler.cpp moc_QZXing.cpp moc_QZXingFilter.cpp moc_platforminformation.cpp moc_threshodltools.cpp moc_downloadworker.cpp moc_useraccount.cpp
moc_ImageHandler.cpp: /Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QObject \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtGui/QImage \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QSet \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QReadWriteLock \
		../ThreeBxConverter/QzXing/ImageHandler.h \
		/Users/christopherforte/Qt/5.10.1/ios/bin/moc
	/Users/christopherforte/Qt/5.10.1/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=9 -D__clang_minor__=1 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/macx-ios-clang -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/common/uikit -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/Core -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing/zxing -I/Users/christopherforte/Qt/5.10.1/ios/include -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQuick -I/Users/christopherforte/Qt/5.10.1/ios/include/QtMultimedia -I/Users/christopherforte/Qt/5.10.1/ios/include/QtGui -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQml -I/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork -I/Users/christopherforte/Qt/5.10.1/ios/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include ../ThreeBxConverter/QzXing/ImageHandler.h -o moc_ImageHandler.cpp

moc_QZXing.cpp: ../ThreeBxConverter/QzXing/QZXing_global.h \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QtGlobal \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QObject \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtGui/QImage \
		../ThreeBxConverter/QzXing/QZXing.h \
		/Users/christopherforte/Qt/5.10.1/ios/bin/moc
	/Users/christopherforte/Qt/5.10.1/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=9 -D__clang_minor__=1 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/macx-ios-clang -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/common/uikit -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/Core -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing/zxing -I/Users/christopherforte/Qt/5.10.1/ios/include -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQuick -I/Users/christopherforte/Qt/5.10.1/ios/include/QtMultimedia -I/Users/christopherforte/Qt/5.10.1/ios/include/QtGui -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQml -I/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork -I/Users/christopherforte/Qt/5.10.1/ios/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include ../ThreeBxConverter/QzXing/QZXing.h -o moc_QZXing.cpp

moc_QZXingFilter.cpp: /Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QObject \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtMultimedia/QAbstractVideoFilter \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QDebug \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QFuture \
		../ThreeBxConverter/QzXing/QZXing.h \
		../ThreeBxConverter/QzXing/QZXing_global.h \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QtGlobal \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtGui/QImage \
		../ThreeBxConverter/QzXing/QZXingFilter.h \
		/Users/christopherforte/Qt/5.10.1/ios/bin/moc
	/Users/christopherforte/Qt/5.10.1/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=9 -D__clang_minor__=1 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/macx-ios-clang -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/common/uikit -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/Core -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing/zxing -I/Users/christopherforte/Qt/5.10.1/ios/include -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQuick -I/Users/christopherforte/Qt/5.10.1/ios/include/QtMultimedia -I/Users/christopherforte/Qt/5.10.1/ios/include/QtGui -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQml -I/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork -I/Users/christopherforte/Qt/5.10.1/ios/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include ../ThreeBxConverter/QzXing/QZXingFilter.h -o moc_QZXingFilter.cpp

moc_platforminformation.cpp: /Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QObject \
		../ThreeBxConverter/platforminformation.h \
		/Users/christopherforte/Qt/5.10.1/ios/bin/moc
	/Users/christopherforte/Qt/5.10.1/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=9 -D__clang_minor__=1 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/macx-ios-clang -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/common/uikit -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/Core -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing/zxing -I/Users/christopherforte/Qt/5.10.1/ios/include -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQuick -I/Users/christopherforte/Qt/5.10.1/ios/include/QtMultimedia -I/Users/christopherforte/Qt/5.10.1/ios/include/QtGui -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQml -I/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork -I/Users/christopherforte/Qt/5.10.1/ios/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include ../ThreeBxConverter/platforminformation.h -o moc_platforminformation.cpp

moc_threshodltools.cpp: /Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QObject \
		../Core/core.h \
		../Core/qstringmath.h \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QString \
		../Core/globalsandconstants.h \
		../ThreeBxConverter/threshodltools.h \
		/Users/christopherforte/Qt/5.10.1/ios/bin/moc
	/Users/christopherforte/Qt/5.10.1/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=9 -D__clang_minor__=1 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/macx-ios-clang -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/common/uikit -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/Core -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing/zxing -I/Users/christopherforte/Qt/5.10.1/ios/include -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQuick -I/Users/christopherforte/Qt/5.10.1/ios/include/QtMultimedia -I/Users/christopherforte/Qt/5.10.1/ios/include/QtGui -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQml -I/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork -I/Users/christopherforte/Qt/5.10.1/ios/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include ../ThreeBxConverter/threshodltools.h -o moc_threshodltools.cpp

moc_downloadworker.cpp: ../Core/core.h \
		../Core/qstringmath.h \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QString \
		../Core/globalsandconstants.h \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QMutex \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QObject \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork/QNetworkAccessManager \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QWaitCondition \
		../ThreeBxConverter/downloadworker.h \
		/Users/christopherforte/Qt/5.10.1/ios/bin/moc
	/Users/christopherforte/Qt/5.10.1/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=9 -D__clang_minor__=1 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/macx-ios-clang -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/common/uikit -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/Core -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing/zxing -I/Users/christopherforte/Qt/5.10.1/ios/include -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQuick -I/Users/christopherforte/Qt/5.10.1/ios/include/QtMultimedia -I/Users/christopherforte/Qt/5.10.1/ios/include/QtGui -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQml -I/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork -I/Users/christopherforte/Qt/5.10.1/ios/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include ../ThreeBxConverter/downloadworker.h -o moc_downloadworker.cpp

moc_useraccount.cpp: /Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QObject \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QMap \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QThread \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QWaitCondition \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QSettings \
		../Core/core.h \
		../Core/qstringmath.h \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QString \
		../Core/globalsandconstants.h \
		../ThreeBxConverter/downloadworker.h \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtCore/QMutex \
		/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork/QNetworkAccessManager \
		../ThreeBxConverter/useraccount.h \
		/Users/christopherforte/Qt/5.10.1/ios/bin/moc
	/Users/christopherforte/Qt/5.10.1/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=9 -D__clang_minor__=1 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/macx-ios-clang -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter -I/Users/christopherforte/Qt/5.10.1/ios/mkspecs/common/uikit -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/Core -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing -I/Users/christopherforte/Documents/ThreeB/Development/ThreeBxConverter/ThreeBxConverter/QzXing/zxing -I/Users/christopherforte/Qt/5.10.1/ios/include -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQuick -I/Users/christopherforte/Qt/5.10.1/ios/include/QtMultimedia -I/Users/christopherforte/Qt/5.10.1/ios/include/QtGui -I/Users/christopherforte/Qt/5.10.1/ios/include/QtQml -I/Users/christopherforte/Qt/5.10.1/ios/include/QtNetwork -I/Users/christopherforte/Qt/5.10.1/ios/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include ../ThreeBxConverter/useraccount.h -o moc_useraccount.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

